### ISSUE TITLE
Using the keyboard to select an option in select menus immediately fails

### ISSUE THREAD

**Issue by rob-3** [KnightHacks/hackathon-2021-frontend#84]
Reproduce:
1. Open register page
2. Press tab until you reach pronouns
3. Press enter
4. Press down arrow
5. Press enter
6. Observe `TypeError: can't convert undefined to object` in logs

**Comment by aileenpongnon** [comment]
unable to reproduce this error on live site

https://user-images.githubusercontent.com/42126081/137230977-46664212-5547-4645-8e4a-a0de05eed6f7.mov

where are you experiencing this bug?
